FROM python:3-buster

ARG DOCKER_WORKDIR
WORKDIR $DOCKER_WORKDIR
COPY requirements-dev.txt ./
RUN pip install --only-binary=netCDF4 -r requirements-dev.txt

COPY scripts/ scripts/
COPY docker/ docker/
